### ISSUE TITLE
MP Lab 1

### ISSUE THREAD

**Issue by correalramos24** [MisterBigThor/FIB-q4#2]
# Tasks

- [ ] Diseño secuencial ➡ Proyecto 3
- [ ] Diseño segmentado ➡ Proyecto 3

# Other tasks

- [ ] Remember LaTeX
- [ ] Explore visual paradigm online
